version: "2"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
     DATABASE_HOST: 127.0.0.1
     POSTGRES_DB: rsdb
     POSTGRES_USER: rsuser
     POSTGRES_PASSWORD: 12345678
    networks: 
     - rs
    volumes:
      - data-volume:/var/lib/db
  web:
    build: .
    command: java -jar /digitalassistant/target/digitalassistant-0.0.1-SNAPSHOT.war
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rsdb
    ports:
      - "8080:8080"
    networks: 
     - rs
    depends_on:
     - db

volumes:
  data-volume:

networks:
  rs: null